notifications:
  email: true

language: cpp
dist: bionic
compiler:
  - gcc

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-ttf-2.0-0
      - libsqlite3-dev
      - python-dev

script:
  - cmake CMakeLists.txt
