notifications:
  email: true

language: cpp
dist: focal
compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libsqlite3-dev
      - python3-dev
      - qtbase5-dev
      - qtdeclarative5-dev
      - qttools5-dev
      - libqt5sql5-sqlite

script:
  - cmake -B ./build
  - cmake --build ./build
