notifications:
  email: true

language: cpp
dist: focal
compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - qt5-qmake
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libsqlite3-dev
      - python3-dev
      - qtbase5-dev
      - qtdeclarative5-dev

script:
  - cmake CMakeLists.txt
  - make
  - cd manager
  - qmake manager.pro
  - make
